### ISSUE TITLE
Since 3 days error connecting to the FCA API

### ISSUE THREAD

**Issue by Bu66as** [Blueion76/FCAUconnect-HA#14]
I have had this message in my log for about 3 days and can no longer get a connection.

Error connecting to the FCA API. 
This can happen from time to time. Retrying in 2 minutes.

I have reactivated the FiatChamp addon as a test, this does not have the problem and can connect to the API.

**Comment by kenirod** [comment]
Same, in debug mode we can see the right data : 

[02151a6d_fca_uconnect_2025-02-02T18-32-02.983Z.log](https://github.com/user-attachments/files/18633445/02151a6d_fca_uconnect_2025-02-02T18-32-02.983Z.log)

**Comment by Blueion76** [comment]
@kenirod @Bu66as I think i've fixed it. Something about the check for vehicle status I was testing in my testing branch was causing the API to error out if it returned data. I couldn't see this as my car doesn't return status 😅

**Comment by kenirod** [comment]
the error is still here and the data doesn't update : 
 [04:49:26 INF] Now fetching new data...
[04:49:26 INF] Mqtt connection successful
[04:49:29 WRN] Error connecting to the FCA API. 
This can happen from time to time. Retrying in 2 minutes.
[04:49:29 INF] Fetching COMPLETED. Next update in 2 minutes.

[04:55:51 WRN] Error connecting to the FCA API. 
This can happen from time to time. Retrying in 2 minutes.
[04:55:51 DBG] ERROR: Response could not be deserialized to JSON: GET https://channels.sdpr-01.fcagcv.com/v1/accounts/XXXXXXXXXXXXX/vehicles/ZFAEFAXXXXXXXX/remote/status    (I put the X)

**Comment by kenirod** [comment]
to be more precise, (english is not my native langage ), the logs show the new data up to date but the entities do not update and are stuck 3 days behind

**Comment by Blueion76** [comment]
> to be more precise, (english is not my native langage ), the logs show the new data up to date but the entities do not update and are stuck 3 days behind

You're all good :) - I'll look into asap tomorrow. It's kind of late here. Apologies.

**Comment by BartKerver** [comment]
Cool new feature coming up !!!

Same issue, some additional info for you on the response for the status-call.

Data returning from Fiat for the status-call seems fine (see response data below for Fiat500E 2023), the whole process than seems to bail-out since the for the other vehicle I have (I have to different VIN's that are connected to my account) the request(s) are not started.

This is the 1.3.5 version of your add-on

---

[10:49:43 WRN] Error connecting to the FCA API. 
This can happen from time to time. Retrying in 5 minutes.
[10:49:43 DBG] ERROR: Response could not be deserialized to JSON: GET https://channels.sdpr-01.fcagcv.com/v1/accounts/--<ACCOUN>--/vehicles/--<VIN>--/remote/status
[10:49:43 DBG] STATUS: 200
[10:49:43 DBG] RESPONSE: {"doors":{"rightRear":{"status":"LOCKED"},"driver":{"status":"LOCKED"},"passenger":{"status":"LOCKED"},"leftRear":{"status":"LOCKED"}},"evRunning":{"status":"OFF"},"trunk":{"status":"LOCKED"},"windows":{"driver":{"status":"CLOSED"},"passenger":{"status":"CLOSED"}},"timestamp":1738427460870}
[10:49:43 INF] Fetching COMPLETED. Next update in 5 minutes.

**Comment by Blueion76** [comment]
@BartKerver @kenirod @Bu66as Also wanted to let you guys know, me and someone else are working on a whole new HACS integration. Check it out here: https://github.com/blind-oracle/hass-fiat/

**Comment by Blueion76** [comment]
Currently working on better docs and a rename to hass-uconnect so be aware an update may break things relatively soon.

**Comment by Blueion76** [comment]
@BartKerver @kenirod @Bu66as New repo should be fully up and running. Migrate over when you get a chance and add your vehicles to the discussion if inclined. :)

https://github.com/hass-uconnect/hass-uconnect

I'll be discontinuing this addon as frankly, it's clunky and unnecessary when a HACS integration can do it all-in-one.
